#
# MySQL environment on docker
#

version: '3'

services:
  # MySQL
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: edumate_db_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE:      edumate
      MYSQL_USER:          edumate
      MYSQL_PASSWORD:      edustudent
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 13306:3306
